# Generated by Django 5.2.10 on 2026-01-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='geojson_endpoint',
            field=models.CharField(blank=True, help_text="Django API endpoint for GeoJSON data, e.g., 'geodata/amsterdam-properties'", max_length=500),
        ),
        migrations.AddField(
            model_name='visualization',
            name='geojson_endpoint',
            field=models.CharField(blank=True, help_text="Django API endpoint for GeoJSON data, e.g., 'geodata/amsterdam-heatmap'", max_length=500),
        ),
        migrations.AlterField(
            model_name='research',
            name='geojson_data',
            field=models.JSONField(blank=True, help_text="GeoJSON data for the article's map (legacy, prefer geojson_endpoint)", null=True),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='geojson_data',
            field=models.JSONField(blank=True, help_text='GeoJSON data for the visualization (legacy, prefer geojson_endpoint)', null=True),
        ),
    ]
