# Generated by Django 5.2.10 on 2026-01-25 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0002_geouploadeddataset_geofeature'),
        ('research', '0002_research_geojson_endpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='geodataset',
            field=models.ForeignKey(blank=True, help_text='Reference to uploaded PostGIS dataset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_articles', to='geodata.geouploadeddataset'),
        ),
        migrations.AddField(
            model_name='research',
            name='value_field',
            field=models.CharField(blank=True, help_text='Field name to use for visualization values', max_length=100),
        ),
        migrations.AddField(
            model_name='visualization',
            name='geodataset',
            field=models.ForeignKey(blank=True, help_text='Reference to uploaded PostGIS dataset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visualizations', to='geodata.geouploadeddataset'),
        ),
        migrations.AddField(
            model_name='visualization',
            name='value_field',
            field=models.CharField(blank=True, help_text='Field name to use for visualization values', max_length=100),
        ),
    ]
