# Generated by Django 5.2.11 on 2026-02-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_researchtranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='PDF version of the research article', null=True, upload_to='research/pdfs/'),
        ),
        migrations.AddField(
            model_name='visualization',
            name='content',
            field=models.TextField(blank=True, help_text='Markdown content for the visualization'),
        ),
    ]
