# Generated by Django 5.2.11 on 2026-02-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_research_pdf_file_visualization_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Preview/thumbnail image for the article', null=True, upload_to='research/previews/'),
        ),
        migrations.AddField(
            model_name='visualization',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Preview/thumbnail image for the visualization', null=True, upload_to='visualizations/previews/'),
        ),
    ]
