# Generated by Django 5.2.11 on 2026-02-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_research_preview_image_visualization_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='preview_image',
            field=models.CharField(blank=True, default='', help_text='URL path for the preview/thumbnail image', max_length=500),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='preview_image',
            field=models.CharField(blank=True, default='', help_text='URL path for the preview/thumbnail image', max_length=500),
        ),
    ]
