# Generated by Django 5.2.11 on 2026-02-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_change_preview_image_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='content',
            field=models.TextField(blank=True, help_text='Markdown content for the article'),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
