# Generated by Django 5.2.10 on 2026-01-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_newsletter_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='access_attempts_today',
        ),
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='last_attempt_date',
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='access_attempts_this_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='current_hour_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
