# Generated by Django 6.0 on 2026-04-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_update_rate_limiting_to_hourly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='access_attempts_this_hour',
        ),
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='access_count',
        ),
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='current_hour_start',
        ),
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='last_access',
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('nl', 'Dutch'), ('it', 'Italian'), ('de', 'German')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='source',
            field=models.CharField(choices=[('footer', 'Footer'), ('post-end', 'Post end'), ('research-end', 'Research end'), ('contact-form', 'Contact form'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
