# Generated by Django 5.2.10 on 2026-01-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('geojson', models.JSONField(help_text='GeoJSON FeatureCollection data')),
                ('region', models.CharField(blank=True, help_text="e.g., 'Amsterdam, NL'", max_length=100)),
                ('data_source', models.CharField(blank=True, help_text='Source of the data', max_length=255)),
                ('last_updated', models.DateField(blank=True, help_text='When the data was last updated', null=True)),
                ('default_center', models.JSONField(default=list, help_text='Default center coordinates [lng, lat]')),
                ('default_zoom', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GeoDataset',
                'verbose_name_plural': 'GeoDatasets',
                'db_table': 'geodatasets',
                'ordering': ['name'],
            },
        ),
    ]
