# Generated by Django 5.2.10 on 2026-01-25 20:31

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoUploadedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_format', models.CharField(choices=[('geojson', 'GeoJSON'), ('gpkg', 'GeoPackage'), ('shp', 'Shapefile')], max_length=20)),
                ('available_fields', models.JSONField(default=list, help_text='List of field names available in the dataset')),
                ('field_types', models.JSONField(default=dict, help_text='Mapping of field names to their data types')),
                ('feature_count', models.IntegerField(default=0)),
                ('bounds', models.JSONField(blank=True, help_text='Bounding box [minx, miny, maxx, maxy]', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Uploaded GeoDataset',
                'verbose_name_plural': 'Uploaded GeoDatasets',
                'db_table': 'geo_uploaded_datasets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeoFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('properties', models.JSONField(default=dict, help_text='All attribute data from the original feature')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='geodata.geouploadeddataset')),
            ],
            options={
                'verbose_name': 'GeoFeature',
                'verbose_name_plural': 'GeoFeatures',
                'db_table': 'geo_features',
                'indexes': [models.Index(fields=['dataset'], name='geo_feature_dataset_9c3537_idx')],
            },
        ),
    ]
